# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Projects', url: '#projects'}
- {name: 'Research', url: 'research'}
- {name: 'Art',      url: 'art'}
- {name: 'Reading',  url: 'reading'}
- {name: 'About',    url: 'about'}
- {name: 'CV',       url: 'assets/pdf/CV Michelle Star (1).pdf'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:mis250@pitt.edu'}

# Customize site text


